services:
  mongodb:
    image: mongo:8
    container_name: notifyhub-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: rabbitmq:4-management
    container_name: notifyhub-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  mongodb_data: